name: Maven Test with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed for gh-pages deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests (with Allure results)
        run: mvn clean test -Dallure.results.directory=target/allure-results || true

      - name: Install Allure CLI
        run: sudo npm install -g allure-commandline --unsafe-perm=true

      - name: Add Allure Executor Info
        run: |
          mkdir -p target/allure-results
          echo '{
            "name": "GitHub Actions",
            "type": "github",
            "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "buildOrder": 1,
            "buildName": "${{ github.workflow }}",
            "buildUrl": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "reportUrl": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/",
            "reportName": "Allure Report"
          }' > target/allure-results/executor.json

      - name: Generate Allure Report
        run: |
          if [ -d "target/allure-results" ] && [ "$(ls -A target/allure-results)" ]; then
            echo "✅ Allure results found. Generating report..."
            allure generate target/allure-results --clean -o allure-report
          else
            echo "⚠️ No Allure results found. Creating placeholder report..."
            mkdir -p allure-report
            echo "<html><body><h1>No Allure results found.</h1></body></html>" > allure-report/index.html
          fi

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true
